### ISSUE TITLE
insert between retrying requests

### ISSUE THREAD

**Issue by lasta** [ymoch/preacher#67]
Hi.
I use preacher to check Apache Solr statuses.
Apache Solr takes several seconds to wake up, so I want to insert sleep time between retrying requests.

**Comment by ymoch** [comment]
Yes, there is no way to change delay between attempts to wait the target to recover.
I wonder if a commandline option help you.

**Comment by ymoch** [comment]
Resolved in #72 and will be released in the next version (maybe `0.10.1`).
Thanks!

**Comment by lasta** [comment]
Thank you to add the command-line option.
That will be very helpful to us.
